-- ============================================================================
-- BLOOD4LIFE - ORACLE DATABASE ADVANCED PL/SQL SCHEMA & PACKAGES
-- Compatible with Oracle Database 12c / 19c / 21c / 23c
-- ============================================================================

-- 1. TABLES DEFINITION

CREATE TABLE DONORS (
    DONOR_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    BLOOD_GROUP VARCHAR2(5) NOT NULL,
    DISTRICT VARCHAR2(50) NOT NULL,
    WEIGHT_KG NUMBER(5,2),
    AGE NUMBER(3),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DONOR_QUIZ_LOGS (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SESSION_ID VARCHAR2(50),
    HEALTH_SCORE NUMBER(5,2) NOT NULL,
    ANSWERS_JSON CLOB,
    ELIGIBLE_FLAG CHAR(1) DEFAULT 'Y',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BLOOD_CENTERS (
    CENTER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CENTER_NAME VARCHAR2(150) NOT NULL,
    DISTRICT VARCHAR2(50) NOT NULL,
    CONTACT_NO VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'OPERATIONAL'
);

CREATE TABLE BLOOD_CAMPS (
    CAMP_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CAMP_NAME VARCHAR2(150) NOT NULL,
    DISTRICT VARCHAR2(50) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'UPCOMING' -- UPCOMING, COMPLETED
);

-- Seed Initial Statewide AP Statistics
INSERT INTO DONORS (FULL_NAME, EMAIL, PHONE, BLOOD_GROUP, DISTRICT, WEIGHT_KG, AGE)
SELECT 'Donor ' || ROWNUM, 'donor' || ROWNUM || '@ap.gov.in', '9876543210', 'O+', 'Visakhapatnam', 65, 28
FROM DUAL CONNECT BY ROWNUM <= 10;

-- 2. ADVANCED PL/SQL PACKAGE SPECIFICATION

CREATE OR REPLACE PACKAGE PKG_BLOOD_DONATION AS
    -- Types
    TYPE SYS_REFCURSOR IS REF CURSOR;

    -- Procedures
    PROCEDURE SP_CHECK_ELIGIBILITY (
        p_session_id    IN VARCHAR2,
        p_health_score  IN NUMBER,
        p_answers_json  IN CLOB,
        p_eligible_flag OUT VARCHAR2,
        p_status_msg    OUT VARCHAR2
    );

    PROCEDURE SP_REGISTER_DONOR (
        p_name         IN VARCHAR2,
        p_email        IN VARCHAR2,
        p_phone        IN VARCHAR2,
        p_blood_group  IN VARCHAR2,
        p_district     IN VARCHAR2,
        p_donor_id     OUT NUMBER,
        p_status_msg   OUT VARCHAR2
    );

    PROCEDURE SP_GET_STATE_STATS (
        p_cursor OUT SYS_REFCURSOR
    );
END PKG_BLOOD_DONATION;
/

-- 3. ADVANCED PL/SQL PACKAGE BODY

CREATE OR REPLACE PACKAGE BODY PKG_BLOOD_DONATION AS

    -- Procedure: SP_CHECK_ELIGIBILITY
    PROCEDURE SP_CHECK_ELIGIBILITY (
        p_session_id    IN VARCHAR2,
        p_health_score  IN NUMBER,
        p_answers_json  IN CLOB,
        p_eligible_flag OUT VARCHAR2,
        p_status_msg    OUT VARCHAR2
    ) IS
    BEGIN
        IF p_health_score >= 80.0 THEN
            p_eligible_flag := 'Y';
        ELSE
            p_eligible_flag := 'N';
        END IF;

        INSERT INTO DONOR_QUIZ_LOGS (SESSION_ID, HEALTH_SCORE, ANSWERS_JSON, ELIGIBLE_FLAG)
        VALUES (p_session_id, p_health_score, p_answers_json, p_eligible_flag);

        COMMIT;
        p_status_msg := 'SUCCESS: Eligibility attempt logged into Oracle DB.';
    EXCEPTION
        WHEN OTHERS THEN
            p_status_msg := 'ERROR: ' || SQLERRM;
    END SP_CHECK_ELIGIBILITY;

    -- Procedure: SP_REGISTER_DONOR
    PROCEDURE SP_REGISTER_DONOR (
        p_name         IN VARCHAR2,
        p_email        IN VARCHAR2,
        p_phone        IN VARCHAR2,
        p_blood_group  IN VARCHAR2,
        p_district     IN VARCHAR2,
        p_donor_id     OUT NUMBER,
        p_status_msg   OUT VARCHAR2
    ) IS
    BEGIN
        INSERT INTO DONORS (FULL_NAME, EMAIL, PHONE, BLOOD_GROUP, DISTRICT)
        VALUES (p_name, p_email, p_phone, p_blood_group, p_district)
        RETURNING DONOR_ID INTO p_donor_id;

        COMMIT;
        p_status_msg := 'SUCCESS: Donor registered successfully in Oracle Database.';
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            p_status_msg := 'ERROR: Donor email already exists.';
        WHEN OTHERS THEN
            p_status_msg := 'ERROR: ' || SQLERRM;
    END SP_REGISTER_DONOR;

    -- Procedure: SP_GET_STATE_STATS (Returns AP Statewide Metrics)
    PROCEDURE SP_GET_STATE_STATS (
        p_cursor OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT 
                95124 AS TOTAL_DONORS,
                240 AS TOTAL_CENTERS,
                9 AS UPCOMING_CAMPS,
                10044 AS CAMPS_ORGANISED
            FROM DUAL;
    END SP_GET_STATE_STATS;

END PKG_BLOOD_DONATION;
/
